/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bigbang.iowaservices.entities;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 *
 * @author sajana
 */
@Entity
public class Skill implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String skill;  
    
    
    //Generated by Map
	private static Map<String,Object> skillValue;
	static{
		skillValue = new LinkedHashMap<String,Object>();
		skillValue.put("Carpentary", "Carpentary"); //label, value
		skillValue.put("Plumbing", "Plumbing");
		skillValue.put("Electrician", "Electrician");
                skillValue.put("Gardenar", "Gardenar"); //label, value
		skillValue.put("Painting", "Painting");
		skillValue.put("Mason", "Mason");

                
	}
 
	public Map<String,Object> getSkillValue() {
		return skillValue;
	}

    public String getSkill() {
        return skill;
    }

    public void setSkill(String spSkill) {
        this.skill = spSkill;
    }
    

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Skill)) {
            return false;
        }
        Skill other = (Skill) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.bigbang.iowaservices.entities.Skill[ id=" + id + " ]";
    }
    
}
